/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#54647a",
        "surface-tint": "#545f73",
        "surface-container-low": "#f5f3f4",
        "tertiary-fixed-dim": "#ddc39d",
        "inverse-on-surface": "#f3f0f2",
        "secondary": "#505f76",
        "tertiary-fixed": "#fadfb8",
        "surface-dim": "#dcd9db",
        "outline": "#75777d",
        "primary-fixed-dim": "#bcc7de",
        "on-tertiary-fixed": "#271902",
        "tertiary": "#1e1200",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "inverse-surface": "#303032",
        "inverse-primary": "#bcc7de",
        "surface-variant": "#e4e2e3",
        "on-primary-fixed-variant": "#3c475a",
        "primary-container": "#1e293b",
        "secondary-fixed": "#d3e4fe",
        "primary": "#091426",
        "background": "#fbf8fa",
        "on-primary-fixed": "#111c2d",
        "surface-container": "#f0edef",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#45474c",
        "surface-container-high": "#eae7e9",
        "primary-fixed": "#d8e3fb",
        "secondary-container": "#d0e1fb",
        "on-tertiary-fixed-variant": "#564427",
        "outline-variant": "#c5c6cd",
        "on-tertiary-container": "#a38c6a",
        "surface": "#fbf8fa",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-container": "#8590a6",
        "tertiary-container": "#35260c",
        "surface-bright": "#fbf8fa",
        "on-surface": "#1b1b1d",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b7c8e1",
        "on-background": "#1b1b1d"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "xs": "4px",
        "md": "16px",
        "xl": "32px",
        "container-margin": "24px",
        "sm": "8px",
        "lg": "24px",
        "base": "4px"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "data-mono": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
